apiVersion: apps/v1
kind: Deployment
metadata:
  name: carwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carwebsite
  template:
    metadata:
      labels:
        app: carwebsite
    spec:
      containers:
      - name: carwebsite
        image: IMAGE_TAG
        ports:
        - containerPort: 80
